[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"
  HUGO_VERSION = "0.127.0"
  HUGO_ENV = "production"

[build]
  command = "git submodule sync && git submodule update --init --recursive && yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "git submodule sync && git submodule update --init --recursive && yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true
