baseurl = "/"
title = "CoastResusGroup"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

# Enable unsafe HTML in markdown (needed for embeds like Calendly)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
    # Enable comments by entering your Disqus shortname
    [services.disqus]
        shortname = "devcows"
    # Enable Google Analytics by entering your tracking code
    [services.googleAnalytics]
        id = ""

# Define the number of posts per page
[pagination]
    pagerSize = 10

# Main menu
[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About"
    identifier = "menu.about"
    url        = "/about/"
    weight     = 2

[[menu.main]]
    name       = "Courses"
    identifier = "menu.courses"
    url        = ""
    weight     = 3

[[menu.main]]
    name       = "ARC ALS Level 1"
    url        = "/als1-basic/"
    weight     = 1
    parent     = "menu.courses"

[[menu.main]]
    name       = "RA ALS Level 1"
    url        = "/ra-als1/"
    weight     = 2
    parent     = "menu.courses"

[[menu.main]]
    name       = "ARC ALS Level 2"
    url        = "/als2-advanced/"
    weight     = 3
    parent     = "menu.courses"

[[menu.main]]
    name       = "RA ALS Level 2"
    url        = "/ra-als2/"
    weight     = 4
    parent     = "menu.courses"

[[menu.main]]
    name       = "Trauma Nursing Core Course (TNCC)"
    url        = "/tncc/"
    weight     = 5
    parent     = "menu.courses"

[[menu.main]]
    name       = "FAQ"
    identifier = "menu.faq"
    url        = "/faq/"
    weight     = 6

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 7


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "X"
    url = "https://x.com"
    pre = "<i class='fab fa-2x fa-x-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hello@universal.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "CoastResusGroup"
    defaultKeywords = ["coastresusgroup", "resuscitation", "medical", "training"]
    mainSections = ["blog"]
    defaultDescription = "CoastResusGroup - Professional resuscitation training and medical education"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Map widget using OpenStreetMap (free, no API key required)
    enableMaps = true

    latitude = "-28.17"
    longitude = "153.54"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # EmailJS configuration - Free email service, no backend required
    # Setup instructions:
    # 1. Sign up at https://www.emailjs.com/ (free tier: 200 emails/month)
    # 2. Create an email service (Gmail, Outlook, etc.)
    # 3. Create an email template
    # 4. Get your Public Key, Service ID, and Template ID from EmailJS dashboard
    # 5. Enter them below
    enableEmailJS = true
    emailjs_public_key = "_KrZ0VDsmSR6Oggjy"
    emailjs_service_id = "service_z8gzxcs"
    emailjs_template_id = "template_4yewmfn"

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    # about_us = "<p>CoastResusGroup provides professional resuscitation training and medical education services.</p>"
    copyright = "Copyright © 2024, CoastResusGroup; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "CoastResusGroup"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    # address = """<p class="text-uppercase"><strong>CoastResusGroup</strong>
    #     <br>Professional Medical Training
    #     <br>Resuscitation Education
    #     <br>Emergency Response Training
    #     <br>
    #     <strong>Contact us for training opportunities</strong>
    #   </p>
    #   """

[permalinks]
    blog = "/blog/:slug/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "What Our Students Say"
    subtitle = "Hear from healthcare professionals who have completed our resuscitation training programs. Their experiences reflect our commitment to excellence in medical education and emergency response training."

[params.see_more]
    enable = true
    icon = "fas fa-users"
    title = "Interested in a private group booking?"
    subtitle = "We offer private bookings for groups of 6 or more. Contact us today to discuss bringing a training session to you."
    link_url = "/contact/"
    link_text = "Contact us"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
